ruby '1.9.3'
source 'https://rubygems.org'

gem 'rails', '3.2.14'
gem 'pg'
gem 'devise'
gem 'simple_form'
gem 'simple_form_fancy_uploads'
gem 'nested_form', :git => 'git://github.com/ryanb/nested_form.git'
gem 'haml-rails'
gem 'jquery-rails'
gem 'inherited_resources'
gem 'state_machine'
gem 'kaminari'
gem 'carrierwave'
gem 'thin'
gem 'mini_magick'
gem 'acts-as-taggable-on'
gem 'friendly_id', '~> 4.0.1'
gem 'carmen', git: 'git://github.com/jim/carmen.git'
gem 'carmen-rails', git: 'git://github.com/jim/carmen-rails.git'
gem 'omniauth'
gem 'omniauth-facebook', git: 'git://github.com/komrade/omniauth-facebook.git'
gem 'fog', '~> 1.0.0'
gem 'bcrypt-ruby', '~> 3.0.0'
gem 'globalize3'
gem 'metamagic'

gem 'bootstrap-wysihtml5-rails'
gem 'twitter-bootstrap-rails'
gem 'less-rails'

gem 'fb_graph', '~> 2.5.0'
gem 'debugger'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'ap'
  gem 'bullet'
  gem 'rails3-generators'
  gem 'awesome_print'
  gem 'pry-rails'
  gem 'random_data'
end

group :test do
  gem 'capybara'
  gem 'cucumber-rails'
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'growl'
  gem 'guard-spork'
  gem 'rb-fsevent'
  gem 'rspec'
  gem 'rspec-mocks'
  gem 'shoulda-matchers'
  gem 'spork-rails'
  gem 'sqlite3'
  gem 'rb-inotify', '~> 0.8.8'
  gem 'annotate', '~> 2.4.1.beta'
  gem 'guard'
  gem 'guard-rails'
  gem 'guard-livereload'
  gem 'guard-spork'
  gem 'guard-rspec'
  gem 'guard-annotate'
  gem 'random_data'
end
